export const GET_POKEMONS 			= 		'GET_POKEMONS'
export const SET_POKEMONS 			= 		'SET_POKEMONS'
export const GET_POKEMON_DETAILS 	= 		'GET_POKEMON_DETAILS'
export const SET_POKEMON_DETAILS 	= 		'SET_POKEMON_DETAILS'